### PR TITLE
Recipe for v0.2.2

### PR DESCRIPTION
**Pull request by muhrin**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Releasing lagacy pytray (v0.2.2) for compatibility with kiwipy which still depends on this version.

### CODE REVIEW

**Comment by muhrin** [comment]
@conda-forge-admin, please rerender

**Comment by ltalirz** [comment]
It's complaining that the specified license file does not exist (perhaps it was added only later?)
They are a bit picky about specifying the license file, so I'm not sure whether it will let you through just deleting the line but it might.

**Comment by muhrin** [comment]
Yes, I forgot the `LICENSE` in the `MANIFEST` so it's not bundled with it on `pypi`.  Let's see if I can get it to work by just removing the reference.

**Comment by muhrin** [comment]
@conda-forge-admin, please rerender

**Comment by ltalirz** [comment]
Looking good!

**Pull request merged**
